# Share and Record Advances
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Share and Record Advances
email: 2328811532@qq.com 
description: > # this means to ignore newlines until "baseurl:"
  As a programmer, I want to improve my ability of coding. By using 
  the website, I will share and record my thoughts.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://lewislongman.github.io" # the base hostname & protocol for your site
github_username:  lewislongman

# Build settings
markdown: kramdown
